#pragma once

struct SAMPLER {};

#include "Engine/D3D12/D3DObject/DescriptorHeap/DescriptorHeap.h"

// インプットレイアウト
namespace Engine::D3D12::Input
{
	// 静的用
	constexpr D3D12_INPUT_ELEMENT_DESC StaticElement[5] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "NORMAL",   0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TANGENT",  0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC StaticLayout = {
		.pInputElementDescs = StaticElement,
		.NumElements = 5
	};

	// アニメーション用
	constexpr D3D12_INPUT_ELEMENT_DESC AnimationInputElement[7] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "NORMAL",     0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD",   0, DXGI_FORMAT_R32G32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TANGENT",    0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",      0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "SKININDEX",  0, DXGI_FORMAT_R16G16B16A16_UINT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
		{ "SKINWEIGHT", 0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0}
	};
	constexpr D3D12_INPUT_LAYOUT_DESC AnimationInputLayout =
	{
		.pInputElementDescs = AnimationInputElement,
		.NumElements = 7
	};

	// 2D描画用
	constexpr D3D12_INPUT_ELEMENT_DESC Static2DElement[2] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
	};
	constexpr D3D12_INPUT_LAYOUT_DESC Static2DLayout = {
		.pInputElementDescs = Static2DElement,
		.NumElements = 2
	};

	// ポジションオンリー
	constexpr D3D12_INPUT_ELEMENT_DESC gPosOnryElement[2] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",      0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC gPosOnryLayout = {
		.pInputElementDescs = gPosOnryElement,
		.NumElements = 2
	};

	// パーティクル描画用
	constexpr D3D12_INPUT_ELEMENT_DESC gParticleInputElement[2] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32A32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD",   0, DXGI_FORMAT_R32G32_FLOAT,	    0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC gParticleInputLayout = {
		.pInputElementDescs = gParticleInputElement,
		.NumElements = 2
	};
}

// ルートシグネチャ
namespace Engine::D3D12
{
	// ルートレンジ指定
	enum class RangeType
	{
		CBV,
		SRV,
		UAV,
		Sampler,
	};

	// ルートパラメーター指定
	enum class RootParameterType
	{
		DescriptorTable,
		RootCBV,
		RootSRV,
		Bindless
	};

	// ルートレンジ用中間構造体
	struct RootRangeInit
	{
		RangeType type;				// レンジタイプ
		UINT shaderRegisterIndex;	// ルート定数などを使用する際のシェーダーインデックス
	};

	// ルートパラメター用中間構造体
	struct RootParamInit
	{
		RootParameterType paramType;				// パラメーター
		std::vector<RootRangeInit> rangeVec = {};	// レンジタイプ・インデックス
		UINT shaderRegisterIndex;					// ルート定数などを使用する際のシェーダーインデックス
	};

	// メッシュシェーダー用パイプラインステート作成用構造体
	struct MeshShaderPipelineStateStream
	{
		CD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE RootSignature;
		CD3DX12_PIPELINE_STATE_STREAM_PRIMITIVE_TOPOLOGY PrimitiveTopologyType;
		CD3DX12_PIPELINE_STATE_STREAM_MS MS;
		CD3DX12_PIPELINE_STATE_STREAM_PS PS;
		CD3DX12_PIPELINE_STATE_STREAM_BLEND_DESC Blend;
		CD3DX12_PIPELINE_STATE_STREAM_RASTERIZER Rasterizer;
		CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL DepthStencil;
		CD3DX12_PIPELINE_STATE_STREAM_RENDER_TARGET_FORMATS RTVFormats;
		CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL_FORMAT DSVFormat;
	};
}