#pragma once

namespace Engine::Graphics::D3D12
{
	// サンプラーのハンドル(Handle<SamplerTag>)を区別するための型
	struct SamplerTag {};
}

// d3dx12.h のうち、ここで使うのはパイプラインステートストリームだけ。
// 一式を読むとプリコンパイル済みヘッダー経由で全翻訳単位に広がるため分割ヘッダーで読む
#pragma warning(push, 0)
#include "d3dx12_pipeline_state_stream.h"
#pragma warning(pop)

#include "Engine/Graphics/D3D12/D3DObject/DescriptorHeap/DescriptorHeap.h"

// インプットレイアウト
namespace Engine::Graphics::D3D12::Input
{
	// 静的用
	constexpr D3D12_INPUT_ELEMENT_DESC STATIC_ELEMENT[5] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "NORMAL",   0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TANGENT",  0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC STATIC_LAYOUT = {
		.pInputElementDescs = STATIC_ELEMENT,
		.NumElements = 5
	};

	// アニメーション用
	constexpr D3D12_INPUT_ELEMENT_DESC ANIMATION_INPUT_ELEMENT[7] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "NORMAL",     0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD",   0, DXGI_FORMAT_R32G32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TANGENT",    0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",      0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "SKININDEX",  0, DXGI_FORMAT_R16G16B16A16_UINT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
		{ "SKINWEIGHT", 0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0}
	};
	constexpr D3D12_INPUT_LAYOUT_DESC ANIMATION_INPUT_LAYOUT =
	{
		.pInputElementDescs = ANIMATION_INPUT_ELEMENT,
		.NumElements = 7
	};

	// 2D描画用
	constexpr D3D12_INPUT_ELEMENT_DESC STATIC_2D_ELEMENT[2] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
	};
	constexpr D3D12_INPUT_LAYOUT_DESC STATIC_2D_LAYOUT = {
		.pInputElementDescs = STATIC_2D_ELEMENT,
		.NumElements = 2
	};

	// ポジションオンリー
	constexpr D3D12_INPUT_ELEMENT_DESC POS_ONLY_ELEMENT[2] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",      0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC POS_ONLY_LAYOUT = {
		.pInputElementDescs = POS_ONLY_ELEMENT,
		.NumElements = 2
	};

	// パーティクル描画用
	constexpr D3D12_INPUT_ELEMENT_DESC PARTICLE_INPUT_ELEMENT[2] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32A32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD",   0, DXGI_FORMAT_R32G32_FLOAT,	    0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC PARTICLE_INPUT_LAYOUT = {
		.pInputElementDescs = PARTICLE_INPUT_ELEMENT,
		.NumElements = 2
	};

	// 空の入力レイアウト。
	// 頂点バッファを読まず SV_VertexID / SV_InstanceID だけで頂点を生成する
	// シェーダー(フルスクリーン描画・デバッグライン等)用。
	// StaticLayout などを宣言してしまうと、IA が頂点バッファを要求し、
	// 直前のパスが残したバッファ(例: パーティクルのクアッド)を読もうとして
	// 「頂点バッファが小さすぎる(#210)」警告が大量に出るため、こちらを使う。
	constexpr D3D12_INPUT_LAYOUT_DESC EMPTY_LAYOUT = {
		.pInputElementDescs = nullptr,
		.NumElements = 0
	};
}

// ルートシグネチャ
namespace Engine::Graphics::D3D12
{
	// ルートレンジ指定
	enum class ERangeType
	{
		CBV,
		SRV,
		UAV,
		Sampler,
	};

	// ルートパラメーター指定
	enum class ERootParameterType
	{
		DescriptorTable,
		RootCBV,
		RootSRV,
		Bindless
	};

	// ルートレンジ用中間構造体
	struct RootRangeInit
	{
		ERangeType type;				// レンジタイプ
		UINT shaderRegisterIndex;	// ルート定数などを使用する際のシェーダーインデックス
	};

	// ルートパラメター用中間構造体
	struct RootParamInit
	{
		ERootParameterType paramType;				// パラメーター
		std::vector<RootRangeInit> rangeVec = {};	// レンジタイプ・インデックス
		UINT shaderRegisterIndex;					// ルート定数などを使用する際のシェーダーインデックス
	};

	// メッシュシェーダー用パイプラインステート作成用構造体
	struct MeshShaderPipelineStateStream
	{
		CD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE RootSignature;
		CD3DX12_PIPELINE_STATE_STREAM_PRIMITIVE_TOPOLOGY PrimitiveTopologyType;
		CD3DX12_PIPELINE_STATE_STREAM_MS MS;
		CD3DX12_PIPELINE_STATE_STREAM_PS PS;
		CD3DX12_PIPELINE_STATE_STREAM_BLEND_DESC Blend;
		CD3DX12_PIPELINE_STATE_STREAM_RASTERIZER Rasterizer;
		CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL DepthStencil;
		CD3DX12_PIPELINE_STATE_STREAM_RENDER_TARGET_FORMATS RTVFormats;
		CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL_FORMAT DSVFormat;
	};
}