#pragma once

// インプットレイアウト
namespace Engine::Graphics::D3D12::Input
{
	// 静的用
	constexpr D3D12_INPUT_ELEMENT_DESC STATIC_ELEMENT[5] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "NORMAL",   0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TANGENT",  0, DXGI_FORMAT_R32G32B32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC STATIC_LAYOUT = {
		.pInputElementDescs = STATIC_ELEMENT,
		.NumElements = 5
	};

	// アニメーション用
	constexpr D3D12_INPUT_ELEMENT_DESC ANIMATION_INPUT_ELEMENT[7] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "NORMAL",     0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD",   0, DXGI_FORMAT_R32G32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TANGENT",    0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",      0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "SKININDEX",  0, DXGI_FORMAT_R16G16B16A16_UINT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
		{ "SKINWEIGHT", 0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0}
	};
	constexpr D3D12_INPUT_LAYOUT_DESC ANIMATION_INPUT_LAYOUT =
	{
		.pInputElementDescs = ANIMATION_INPUT_ELEMENT,
		.NumElements = 7
	};

	// 2D描画用
	constexpr D3D12_INPUT_ELEMENT_DESC STATIC_2D_ELEMENT[2] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
	};
	constexpr D3D12_INPUT_LAYOUT_DESC STATIC_2D_LAYOUT = {
		.pInputElementDescs = STATIC_2D_ELEMENT,
		.NumElements = 2
	};

	// ポジションオンリー
	constexpr D3D12_INPUT_ELEMENT_DESC POS_ONLY_ELEMENT[2] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR",      0, DXGI_FORMAT_R32G32B32A32_FLOAT,	0, D3D12_APPEND_ALIGNED_ELEMENT,D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC POS_ONLY_LAYOUT = {
		.pInputElementDescs = POS_ONLY_ELEMENT,
		.NumElements = 2
	};

	// パーティクル描画用
	constexpr D3D12_INPUT_ELEMENT_DESC PARTICLE_INPUT_ELEMENT[2] =
	{
		{ "POSITION",   0, DXGI_FORMAT_R32G32B32A32_FLOAT,		0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "TEXCOORD",   0, DXGI_FORMAT_R32G32_FLOAT,	    0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};
	constexpr D3D12_INPUT_LAYOUT_DESC PARTICLE_INPUT_LAYOUT = {
		.pInputElementDescs = PARTICLE_INPUT_ELEMENT,
		.NumElements = 2
	};

	// 空の入力レイアウト。
	// 頂点バッファを読まず SV_VertexID / SV_InstanceID だけで頂点を生成する
	// シェーダー(フルスクリーン描画・デバッグライン等)用。
	// StaticLayout などを宣言してしまうと、IA が頂点バッファを要求し、
	// 直前のパスが残したバッファ(例: パーティクルのクアッド)を読もうとして
	// 「頂点バッファが小さすぎる(#210)」警告が大量に出るため、こちらを使う。
	constexpr D3D12_INPUT_LAYOUT_DESC EMPTY_LAYOUT = {
		.pInputElementDescs = nullptr,
		.NumElements = 0
	};
}
